// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: fraud.proto

package fraudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_DECISION_APPROVED    Decision = 1
	Decision_DECISION_REJECTED    Decision = 2
	Decision_DECISION_REVIEW      Decision = 3
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_APPROVED",
		2: "DECISION_REJECTED",
		3: "DECISION_REVIEW",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"DECISION_APPROVED":    1,
		"DECISION_REJECTED":    2,
		"DECISION_REVIEW":      3,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_fraud_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_fraud_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_fraud_proto_rawDescGZIP(), []int{0}
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_fraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_fraud_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *EvaluateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EvaluateRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *EvaluateRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *EvaluateRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type EvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Decision      Decision               `protobuf:"varint,2,opt,name=decision,proto3,enum=fintech.fraud.v1.Decision" json:"decision,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_fraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_fraud_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *EvaluateResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *EvaluateResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_fraud_proto protoreflect.FileDescriptor

const file_fraud_proto_rawDesc = "" +
	"\n" +
	"\vfraud.proto\x12\x10fintech.fraud.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x01\n" +
	"\x0fEvaluateRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\tR\bwalletId\x12!\n" +
	"\famount_cents\x18\x04 \x01(\x03R\vamountCents\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\x89\x01\n" +
	"\x10EvaluateResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x126\n" +
	"\bdecision\x18\x02 \x01(\x0e2\x1a.fintech.fraud.v1.DecisionR\bdecision\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*g\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DECISION_APPROVED\x10\x01\x12\x15\n" +
	"\x11DECISION_REJECTED\x10\x02\x12\x13\n" +
	"\x0fDECISION_REVIEW\x10\x032c\n" +
	"\fFraudService\x12S\n" +
	"\bEvaluate\x12!.fintech.fraud.v1.EvaluateRequest\x1a\".fintech.fraud.v1.EvaluateResponse\"\x00BNZLgithub.com/DeSouzaRafael/go-fintech-microservices/api/proto/fraud/v1;fraudv1b\x06proto3"

var (
	file_fraud_proto_rawDescOnce sync.Once
	file_fraud_proto_rawDescData []byte
)

func file_fraud_proto_rawDescGZIP() []byte {
	file_fraud_proto_rawDescOnce.Do(func() {
		file_fraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fraud_proto_rawDesc), len(file_fraud_proto_rawDesc)))
	})
	return file_fraud_proto_rawDescData
}

var file_fraud_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fraud_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fraud_proto_goTypes = []any{
	(Decision)(0),                 // 0: fintech.fraud.v1.Decision
	(*EvaluateRequest)(nil),       // 1: fintech.fraud.v1.EvaluateRequest
	(*EvaluateResponse)(nil),      // 2: fintech.fraud.v1.EvaluateResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_fraud_proto_depIdxs = []int32{
	3, // 0: fintech.fraud.v1.EvaluateRequest.occurred_at:type_name -> google.protobuf.Timestamp
	0, // 1: fintech.fraud.v1.EvaluateResponse.decision:type_name -> fintech.fraud.v1.Decision
	1, // 2: fintech.fraud.v1.FraudService.Evaluate:input_type -> fintech.fraud.v1.EvaluateRequest
	2, // 3: fintech.fraud.v1.FraudService.Evaluate:output_type -> fintech.fraud.v1.EvaluateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fraud_proto_init() }
func file_fraud_proto_init() {
	if File_fraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fraud_proto_rawDesc), len(file_fraud_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fraud_proto_goTypes,
		DependencyIndexes: file_fraud_proto_depIdxs,
		EnumInfos:         file_fraud_proto_enumTypes,
		MessageInfos:      file_fraud_proto_msgTypes,
	}.Build()
	File_fraud_proto = out.File
	file_fraud_proto_goTypes = nil
	file_fraud_proto_depIdxs = nil
}
